theme: jekyll-theme-midnight
title: "Práctica 6: Clases e interfaces genéricas. Principios SOLID"
description: "Resolución de una serie de ejercicios de programación que nos permitirán conocer más en profundidad las clases e interfaces genéricas del lenguaje TypeScript."
